use_frameworks!

target 'UserHook_Example' do
  pod 'UserHook', :path => '../'

  target 'UserHook_Tests' do
    inherit! :search_paths
    
    pod 'UserHook', :path => '../'
    pod 'OCMock'
    
  end
end
